---

palo_provider:
  #api_key: LUFRPT1vcmFQNVpFTUpTeUVQOWdrVDZJZkszc1d6dW89d1FOQlRCZTgvUFRyL0laNHBhKytlbHVGSEVCWGlOQkpCRDlIdERGOUxjWGpTWEVDVHNwMVhXd2o3TmdjdlZ5ZQ==
  ip_address: "{{ ansible_host }}"
  username: 'admin'
  password: 'NQ9mbXWC7JCfpFNpr'

adminusername: admin
adminpassword: NQ9mbXWC7JCfpFNpr

ansible_ssh_user: admin
ansible_ssh_pass: Cisco123

dns_primary_ip: "8.8.8.8"
dns_secondary_ip: "2.2.2.2"
panorama_primary_ip: "192.168.1.212"
panorama_secondary_ip: "4.4.4.4"
ntp_server_primary_ip: "5.5.5.5"
ntp_server_secondary_ip: "6.6.6.6"

